"""FastAPI app factory + lifespan.

Minimal for Tier A — full route wiring in Tier B B8.
"""
from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.config import settings

logging.basicConfig(
    level=getattr(logging, settings.app_log_level.upper(), logging.INFO),
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup + shutdown hooks."""
    logger.info("VC Brain backend starting (env=%s)", settings.app_env)
    # Pre-warm the embeddings model in a background thread
    try:
        from app.utils.embeddings import embed_text

        await embed_text("warmup")
    except Exception as e:
        logger.warning("Embedding warmup failed (will retry lazily): %s", e)
    yield
    logger.info("VC Brain backend shutting down")


def create_app() -> FastAPI:
    app = FastAPI(
        title="VC Brain",
        description="Agentic investment screening OS",
        version="0.1.0",
        lifespan=lifespan,
    )

    # CORS — allow the Vite dev server
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["http://localhost:5173", "http://localhost:3000", "http://127.0.0.1:5173"],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.get("/health")
    async def health() -> dict:
        return {"status": "ok", "env": settings.app_env}

    # Serve dataset/assets/* as static files so the frontend can load
    # local-fallback SVGs (initials avatars + campus icons) generated by
    # scripts/dataset/generate_founders.py.
    assets_dir = Path(__file__).resolve().parent.parent.parent / "dataset" / "assets"
    if assets_dir.exists():
        app.mount("/dataset/assets", StaticFiles(directory=str(assets_dir)), name="dataset-assets")
        logger.info("Mounted static assets at /dataset/assets → %s", assets_dir)

    # API routes — wire all routers from app.api.router
    try:
        from app.api.router import router as api_router

        app.include_router(api_router, prefix="/api")
    except Exception as e:
        logger.exception("Failed to load API router: %s", e)
        raise

    return app


app = create_app()
